/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export interface JobApplication {
  'name' : string,
  'experienceYears' : bigint,
  'timestamp' : Timestamp,
  'phone' : string,
  'position' : Position,
}
export type Position = { 'apprenticeCarpenter' : null } |
  { 'siteSupervisor' : null } |
  { 'carpenter' : null };
export type Timestamp = bigint;
export interface _SERVICE {
  'getAllContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllJobApplications' : ActorMethod<[], Array<JobApplication>>,
  'getContactByTimestamp' : ActorMethod<[Timestamp], ContactSubmission>,
  'getJobApplicationByTimestamp' : ActorMethod<[Timestamp], JobApplication>,
  'submitContact' : ActorMethod<[string, string, string, string], undefined>,
  'submitJobApplication' : ActorMethod<
    [string, string, bigint, Position],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];