/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const Position = IDL.Variant({
  'apprenticeCarpenter' : IDL.Null,
  'siteSupervisor' : IDL.Null,
  'carpenter' : IDL.Null,
});
export const JobApplication = IDL.Record({
  'name' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'position' : Position,
});

export const idlService = IDL.Service({
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'getAllJobApplications' : IDL.Func([], [IDL.Vec(JobApplication)], []),
  'getContactByTimestamp' : IDL.Func(
      [Timestamp],
      [ContactSubmission],
      ['query'],
    ),
  'getJobApplicationByTimestamp' : IDL.Func([Timestamp], [JobApplication], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitJobApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Position],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const Position = IDL.Variant({
    'apprenticeCarpenter' : IDL.Null,
    'siteSupervisor' : IDL.Null,
    'carpenter' : IDL.Null,
  });
  const JobApplication = IDL.Record({
    'name' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'position' : Position,
  });
  
  return IDL.Service({
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'getAllJobApplications' : IDL.Func([], [IDL.Vec(JobApplication)], []),
    'getContactByTimestamp' : IDL.Func(
        [Timestamp],
        [ContactSubmission],
        ['query'],
      ),
    'getJobApplicationByTimestamp' : IDL.Func(
        [Timestamp],
        [JobApplication],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitJobApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Position],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };